// Generated by gencpp from file my_msgs/CustomString.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_CUSTOMSTRING_H
#define MY_MSGS_MESSAGE_CUSTOMSTRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct CustomString_
{
  typedef CustomString_<ContainerAllocator> Type;

  CustomString_()
    : my_data()  {
    }
  CustomString_(const ContainerAllocator& _alloc)
    : my_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _my_data_type;
  _my_data_type my_data;





  typedef boost::shared_ptr< ::my_msgs::CustomString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::CustomString_<ContainerAllocator> const> ConstPtr;

}; // struct CustomString_

typedef ::my_msgs::CustomString_<std::allocator<void> > CustomString;

typedef boost::shared_ptr< ::my_msgs::CustomString > CustomStringPtr;
typedef boost::shared_ptr< ::my_msgs::CustomString const> CustomStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::CustomString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::CustomString_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_msgs::CustomString_<ContainerAllocator1> & lhs, const ::my_msgs::CustomString_<ContainerAllocator2> & rhs)
{
  return lhs.my_data == rhs.my_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_msgs::CustomString_<ContainerAllocator1> & lhs, const ::my_msgs::CustomString_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_msgs::CustomString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::CustomString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::CustomString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::CustomString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::CustomString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::CustomString_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::CustomString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "812e5b0223ac4003b51dc6f4c4f8fcbf";
  }

  static const char* value(const ::my_msgs::CustomString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x812e5b0223ac4003ULL;
  static const uint64_t static_value2 = 0xb51dc6f4c4f8fcbfULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::CustomString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/CustomString";
  }

  static const char* value(const ::my_msgs::CustomString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::CustomString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string my_data\n"
;
  }

  static const char* value(const ::my_msgs::CustomString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::CustomString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.my_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::CustomString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::CustomString_<ContainerAllocator>& v)
  {
    s << indent << "my_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.my_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_CUSTOMSTRING_H
